// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/player/player.proto

package player

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PlayerService service

type PlayerService interface {
	GetPlayer(ctx context.Context, in *PlayerRequest, opts ...client.CallOption) (*PlayerResponse, error)
}

type playerService struct {
	c    client.Client
	name string
}

func NewPlayerService(name string, c client.Client) PlayerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "playerservice"
	}
	return &playerService{
		c:    c,
		name: name,
	}
}

func (c *playerService) GetPlayer(ctx context.Context, in *PlayerRequest, opts ...client.CallOption) (*PlayerResponse, error) {
	req := c.c.NewRequest(c.name, "PlayerService.GetPlayer", in)
	out := new(PlayerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlayerService service

type PlayerServiceHandler interface {
	GetPlayer(context.Context, *PlayerRequest, *PlayerResponse) error
}

func RegisterPlayerServiceHandler(s server.Server, hdlr PlayerServiceHandler, opts ...server.HandlerOption) error {
	type playerService interface {
		GetPlayer(ctx context.Context, in *PlayerRequest, out *PlayerResponse) error
	}
	type PlayerService struct {
		playerService
	}
	h := &playerServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PlayerService{h}, opts...))
}

type playerServiceHandler struct {
	PlayerServiceHandler
}

func (h *playerServiceHandler) GetPlayer(ctx context.Context, in *PlayerRequest, out *PlayerResponse) error {
	return h.PlayerServiceHandler.GetPlayer(ctx, in, out)
}
