// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/player/player.proto

package player

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerRequest struct {
	PlayerGUID           string   `protobuf:"bytes,1,opt,name=PlayerGUID,proto3" json:"PlayerGUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRequest) Reset()         { *m = PlayerRequest{} }
func (m *PlayerRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerRequest) ProtoMessage()    {}
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c3948187e091db4, []int{0}
}

func (m *PlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRequest.Unmarshal(m, b)
}
func (m *PlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRequest.Marshal(b, m, deterministic)
}
func (m *PlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRequest.Merge(m, src)
}
func (m *PlayerRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerRequest.Size(m)
}
func (m *PlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRequest proto.InternalMessageInfo

func (m *PlayerRequest) GetPlayerGUID() string {
	if m != nil {
		return m.PlayerGUID
	}
	return ""
}

type PlayerResponse struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerResponse) Reset()         { *m = PlayerResponse{} }
func (m *PlayerResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerResponse) ProtoMessage()    {}
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c3948187e091db4, []int{1}
}

func (m *PlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerResponse.Unmarshal(m, b)
}
func (m *PlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerResponse.Marshal(b, m, deterministic)
}
func (m *PlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerResponse.Merge(m, src)
}
func (m *PlayerResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerResponse.Size(m)
}
func (m *PlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerResponse proto.InternalMessageInfo

func (m *PlayerResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	MapGUID              string   `protobuf:"bytes,3,opt,name=mapGUID,proto3" json:"mapGUID,omitempty"`
	XPos                 int64    `protobuf:"varint,4,opt,name=xPos,proto3" json:"xPos,omitempty"`
	YPos                 int64    `protobuf:"varint,5,opt,name=yPos,proto3" json:"yPos,omitempty"`
	Health               int64    `protobuf:"varint,6,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth            int64    `protobuf:"varint,7,opt,name=maxHealth,proto3" json:"maxHealth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c3948187e091db4, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Player) GetMapGUID() string {
	if m != nil {
		return m.MapGUID
	}
	return ""
}

func (m *Player) GetXPos() int64 {
	if m != nil {
		return m.XPos
	}
	return 0
}

func (m *Player) GetYPos() int64 {
	if m != nil {
		return m.YPos
	}
	return 0
}

func (m *Player) GetHealth() int64 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Player) GetMaxHealth() int64 {
	if m != nil {
		return m.MaxHealth
	}
	return 0
}

type MovementEvent struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XPos                 int64    `protobuf:"varint,3,opt,name=xPos,proto3" json:"xPos,omitempty"`
	YPos                 int64    `protobuf:"varint,4,opt,name=yPos,proto3" json:"yPos,omitempty"`
	MapGUID              string   `protobuf:"bytes,5,opt,name=mapGUID,proto3" json:"mapGUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovementEvent) Reset()         { *m = MovementEvent{} }
func (m *MovementEvent) String() string { return proto.CompactTextString(m) }
func (*MovementEvent) ProtoMessage()    {}
func (*MovementEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c3948187e091db4, []int{3}
}

func (m *MovementEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovementEvent.Unmarshal(m, b)
}
func (m *MovementEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovementEvent.Marshal(b, m, deterministic)
}
func (m *MovementEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovementEvent.Merge(m, src)
}
func (m *MovementEvent) XXX_Size() int {
	return xxx_messageInfo_MovementEvent.Size(m)
}
func (m *MovementEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MovementEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MovementEvent proto.InternalMessageInfo

func (m *MovementEvent) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *MovementEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MovementEvent) GetXPos() int64 {
	if m != nil {
		return m.XPos
	}
	return 0
}

func (m *MovementEvent) GetYPos() int64 {
	if m != nil {
		return m.YPos
	}
	return 0
}

func (m *MovementEvent) GetMapGUID() string {
	if m != nil {
		return m.MapGUID
	}
	return ""
}

func init() {
	proto.RegisterType((*PlayerRequest)(nil), "PlayerRequest")
	proto.RegisterType((*PlayerResponse)(nil), "PlayerResponse")
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*MovementEvent)(nil), "MovementEvent")
}

func init() { proto.RegisterFile("proto/player/player.proto", fileDescriptor_7c3948187e091db4) }

var fileDescriptor_7c3948187e091db4 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0xf9, 0x27, 0x4d, 0xcc, 0x48, 0x2b, 0xec, 0x41, 0x62, 0x29, 0x5a, 0x72, 0xea,
	0x69, 0x8b, 0xf5, 0x01, 0xbc, 0x28, 0xd5, 0x83, 0x50, 0x22, 0x3e, 0xc0, 0x2a, 0x03, 0x2d, 0x74,
	0xb3, 0x6b, 0x76, 0x1b, 0xda, 0xb3, 0x2f, 0xe4, 0x23, 0x4a, 0x66, 0x37, 0x6d, 0x02, 0x3d, 0x65,
	0xbe, 0xdf, 0xec, 0x0c, 0xdf, 0xe4, 0x83, 0x1b, 0x5d, 0x29, 0xab, 0xe6, 0x7a, 0x2b, 0x0e, 0x58,
	0xf9, 0x0f, 0x27, 0x96, 0xcf, 0x61, 0xb8, 0x22, 0x5d, 0xe0, 0xf7, 0x0e, 0x8d, 0x65, 0xb7, 0x00,
	0x0e, 0x2c, 0x3f, 0x5e, 0x9f, 0xb2, 0x60, 0x1a, 0xcc, 0xd2, 0xa2, 0x43, 0xf2, 0x7b, 0x18, 0xb5,
	0x03, 0x46, 0xab, 0xd2, 0x20, 0xbb, 0x83, 0xd8, 0xad, 0xa4, 0xd7, 0x97, 0x8b, 0x84, 0xfb, 0x07,
	0x1e, 0xe7, 0xbf, 0x01, 0xc4, 0x0e, 0x31, 0x06, 0x51, 0x67, 0x2f, 0xd5, 0x6c, 0x0c, 0x17, 0x3b,
	0x83, 0x55, 0x29, 0x24, 0x66, 0xff, 0x89, 0x1f, 0x35, 0xcb, 0x20, 0x91, 0x42, 0xd3, 0x48, 0x48,
	0xad, 0x56, 0x36, 0x9b, 0xf6, 0x2b, 0x65, 0xb2, 0x68, 0x1a, 0xcc, 0xc2, 0x82, 0xea, 0x86, 0x1d,
	0x1a, 0x36, 0x70, 0xac, 0xa9, 0xd9, 0x35, 0xc4, 0x6b, 0x14, 0x5b, 0xbb, 0xce, 0x62, 0xa2, 0x5e,
	0xb1, 0x09, 0xa4, 0x52, 0xec, 0x5f, 0x5c, 0x2b, 0xa1, 0xd6, 0x09, 0xe4, 0x3f, 0x01, 0x0c, 0xdf,
	0x54, 0x8d, 0x12, 0x4b, 0xfb, 0x5c, 0x63, 0x69, 0xcf, 0x3a, 0x9f, 0x40, 0x6a, 0x37, 0x12, 0x8d,
	0x15, 0x52, 0x93, 0xf5, 0xb0, 0x38, 0x81, 0xa3, 0xc3, 0xf0, 0x8c, 0xc3, 0xa8, 0xe3, 0xb0, 0x73,
	0xe3, 0xa0, 0x77, 0xe3, 0xe2, 0xb1, 0x0d, 0xe7, 0x1d, 0xab, 0x7a, 0xf3, 0x85, 0x8c, 0x43, 0xba,
	0x44, 0xeb, 0xff, 0xe5, 0x88, 0xf7, 0x92, 0x1b, 0x5f, 0xf1, 0x7e, 0x30, 0xf9, 0xbf, 0xcf, 0x98,
	0x42, 0x7e, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x7f, 0x98, 0x94, 0x01, 0x02, 0x00, 0x00,
}
