// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: player.proto

package player

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Player service

type PlayerService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type playerService struct {
	c    client.Client
	name string
}

func NewPlayerService(name string, c client.Client) PlayerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "player"
	}
	return &playerService{
		c:    c,
		name: name,
	}
}

func (c *playerService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Player.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Player service

type PlayerHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterPlayerHandler(s server.Server, hdlr PlayerHandler, opts ...server.HandlerOption) error {
	type player interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type Player struct {
		player
	}
	h := &playerHandler{hdlr}
	return s.Handle(s.NewHandler(&Player{h}, opts...))
}

type playerHandler struct {
	PlayerHandler
}

func (h *playerHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.PlayerHandler.Hello(ctx, in, out)
}
